spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: mms
    password: password
    url: jdbc:postgresql://localhost:5432/mms
  application:
    name: MemberManagementSystem
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      table-name: spring_session
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
